package:
  name: "pynytimes"
  version: "0.10.1"

source:
  git_rev: v0.10.1
  git_url: https://github.com/michadenheijer/pynytimes

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - "python>=3.9,<4"
    - requests

about:
  home: https://github.com/michadenheijer/pynytimes
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Use all the New York Times APIs in Python!"

extra:
  recipe-maintainers:
    - michadenheijer