"""Version data for the pynytimes library"""
__title__ = "pynytimes"
__description__ = "A Python wrapper for (most) New York Times APIs"
__url__ = "https://pynytimes.michadenheijer.com/"
__version__ = "0.10.1"
__author__ = "Micha den Heijer"
__author_email__ = "micha@michadenheijer.com"
__license__ = "MIT"
__copyright__ = "(c) 2019 - 2023 Micha den Heijer"
