name: Python package

on: [push]

jobs:
  linux-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", pypy3]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Set API key
        env:
          NewYorkTimesAPIKey: ${{ secrets.API_KEY }}
      - name: Run unittests
        run: |
          python tests.py

  windows-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Set API key
        env:
          NewYorkTimesAPIKey: ${{ secrets.API_KEY }}
      - name: Run unittests
        run: |
          python tests.py

  macos-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Set API key
        env:
          NewYorkTimesAPIKey: ${{ secrets.API_KEY }}
      - name: Run unittests
        run: |
          python tests.py
